services:
  mkdocs:
    image: squidfunk/mkdocs-material:latest
    container_name: mkdocs_wiki
    restart: unless-stopped
    ports:
      - "${MKDOCS_PORT:-8000}:8000"
    volumes:
      - .:/docs
    env_file:
      - .env
    # Instalamos o plugin e subimos o serviço
    entrypoint: >
      sh -c "pip install mkdocs-macros-plugin && 
             mkdocs serve --dev-addr 0.0.0.0:8000 --config-file ${MKDOCS_CONFIG_FILE:-mkdocs.yml}"
