site_name: "{{ env.SITE_NAME | default('Confi Wiki') }}"
site_description: "{{ env.SITE_DESCRIPTION | default('Docs') }}"

theme:
  name: material
  language: pt-BR
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Modo Escuro
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Modo Claro
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - search.suggest
    - search.highlight

plugins:
  - search
  - macros # Essencial para ler o .env
